#!/bin/bash

EXEC_DATE=`date '+%Y%m%d'`

./tile-controller/exec >> log/controller-$EXEC_DATE.log 2>&1 &
./tile-view/exec >> log/view-$EXEC_DATE.log 2>&1 &
# ./hw-observer/exec 2>&1 log/hardware-$EXEC_DATE.log &
wait
